const { validSession, toolName } = require("./access-auth");

function page(body) { return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>My Tools | Body Connection Nutrition</title><link rel="stylesheet" href="/assets/css/style.css"></head><body><main class="container" style="max-width:900px;padding:4rem 1.25rem"><p class="eyebrow">Body Connection Nutrition</p>${body}</main></body></html>`; }

exports.handler = async event => {
  let session = null;
  try { session = await validSession(event); } catch (error) { console.error(error); }
  if (!session) return { statusCode: 200, headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "private, no-store" }, body: page(`<h1>Open your purchased tools</h1><p>Enter the email used at Stripe checkout. We will send a private, one-use link that expires in 15 minutes.</p><form id="access-form" style="max-width:520px"><label><strong>Checkout email</strong><input style="display:block;width:100%;margin:.5rem 0 1rem;padding:.8rem" type="email" name="email" autocomplete="email" required></label><button class="button" type="submit">Email my sign-in link →</button></form><p id="message" aria-live="polite"></p><p><a href="/purchase-support/">Need purchase help?</a></p><script>document.getElementById('access-form').addEventListener('submit',async function(e){e.preventDefault();const b=e.currentTarget.querySelector('button'),m=document.getElementById('message');b.disabled=true;m.textContent='Sending…';try{const r=await fetch('/.netlify/functions/request-access',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(e.currentTarget))});const d=await r.json();m.textContent=d.message;}catch(_){m.textContent='We could not send the link. Please try again.';}b.disabled=false;});if(new URLSearchParams(location.search).get('link')==='invalid')document.getElementById('message').textContent='That sign-in link has expired or was already used. Request a new one below.';</script>`) };
  const cards = session.grants.map(slug => `<article class="card"><h2>${toolName(slug)}</h2><p><a class="button" href="/.netlify/functions/paid-tool?product=${encodeURIComponent(slug)}">Open tool →</a></p></article>`).join("");
  return { statusCode: 200, headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "private, no-store" }, body: page(`<h1>My Tools</h1><p>Signed in as ${session.email.replace(/</g, "&lt;")}. You can use access on up to three verified browsers.</p><div class="card-grid">${cards}</div><p><a href="/.netlify/functions/logout-access">Sign out of this browser</a> · <a href="/purchase-support/">Purchase help</a></p>`) };
};
