const crypto = require("crypto");
const COOKIE_NAME = "bcn_patient_tools";

function secret(){ return process.env.PATIENT_TOOLS_PASSWORD || ""; }
function expected(){ const s=secret(); return s ? crypto.createHmac("sha256",s).update("body-connection-patient-tools-v1").digest("base64url") : ""; }
function cookies(header=""){ return Object.fromEntries(header.split(";").map(x=>x.trim()).filter(Boolean).map(p=>{const i=p.indexOf("=");return i<0?[p,""]:[p.slice(0,i),decodeURIComponent(p.slice(i+1))];})); }
function authed(event){ const e=expected(); if(!e)return false; const a=Buffer.from((cookies(event.headers.cookie||event.headers.Cookie||"")[COOKIE_NAME])||""), b=Buffer.from(e); return a.length===b.length&&a.length>0&&crypto.timingSafeEqual(a,b); }
function headers(extra={}){return{"Content-Type":"text/html; charset=utf-8","Cache-Control":"private, no-store, max-age=0","X-Robots-Tag":"noindex, nofollow",...extra};}
function page(body){return`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Patient Tools | Body Connection Nutrition</title><style>:root{--d:#31412f;--c:#c89468;--bg:#fbf7ef;--line:#ded8ce}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#2e2b27;font:16px/1.6 system-ui}.wrap{width:min(980px,92%);margin:auto;padding:4rem 0}h1,h2,h3{font-family:Georgia,serif;color:var(--d)}h1{font-size:clamp(2.5rem,6vw,4.5rem)}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:1rem}.card,.note{background:#fff;border:1px solid var(--line);border-radius:20px;padding:1.3rem}.note{border-left:4px solid var(--c);margin:1.5rem 0}.meta{color:var(--c);font-weight:800;text-transform:uppercase;letter-spacing:.08em;font-size:.76rem}.btn{display:inline-block;background:var(--d);color:#fff;text-decoration:none;border-radius:999px;padding:.75rem 1rem;font-weight:800}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style></head><body><main class="wrap">${body}</main></body></html>`;}
exports.handler=async(event)=>{
  if((event.queryStringParameters||{}).logout==="1") return {statusCode:302,headers:{Location:"/patient-tools/","Set-Cookie":`${COOKIE_NAME}=; Path=/patient-tools; Max-Age=0; HttpOnly; Secure; SameSite=Lax`,`Cache-Control":"no-store"},body:""};
  if(!authed(event)) return {statusCode:302,headers:{Location:"/.netlify/functions/patient-tools?path=","Cache-Control":"no-store"},body:""};
  const body=`<p class="meta">Patient learning space</p><h1>Body Connection tools</h1><p>These tools are available to you as part of your work with Body Connection Nutrition.</p><div class="note"><b>You do not need to complete these in order.</b> Use the tool that connects most directly to what you are working on.</div><div class="grid"><article class="card"><p class="meta">Notice</p><h3>Can You Hear Your Body?</h3><p>Explore signal, interpretation, and permission.</p><a class="btn" href="/tools/can-you-hear-your-body/">Open →</a></article><article class="card"><p class="meta">Eating moment</p><h3>Why Am I Eating?</h3><p>Examine one food decision in context.</p><a class="btn" href="/patient-tools/why-am-i-eating">Open →</a></article><article class="card"><p class="meta">Food influences</p><h3>Who Taught You to Eat?</h3><p>Map influences on everyday eating.</p><a class="btn" href="/patient-tools/who-taught-you-to-eat">Open →</a></article><article class="card"><p class="meta">Body-image influences</p><h3>How Was My Body Image Created?</h3><p>Map influences on body image.</p><a class="btn" href="/patient-tools/how-was-my-body-image-created">Open →</a></article><article class="card"><p class="meta">One belief</p><h3>Deconstructing a Belief</h3><p>Trace how one belief became convincing.</p><a class="btn" href="/patient-tools/deconstructing-a-belief">Open →</a></article></div><p><a href="/patient-tools/logout">Sign out</a></p>`;
  return {statusCode:200,headers:headers(),body:page(body)};
};