title: "Body Connection Nutrition"
description: "A path to peace with your body through nutrition, embodiment, and compassion."
url: "https://bodyconnectionnutrition.com"
baseurl: ""

markdown: kramdown
permalink: /reflections/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
